name: "Release: 2. Automatic Tagging"
on:
  push:
    branches:
      - stable

jobs:
  tag:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Environment
        run: |
          php .github/release.php current >> $GITHUB_ENV

      - name: Check if a tag already exists
        run: |
          if git rev-parse "release-${{ env.current_version }}" >/dev/null 2>&1; then
            echo "::error::Tag already exists, be sure to update the VERSION file for a hotfix"
            exit 1
          fi

      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            const {current_version} = process.env;
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/release-${current_version}`,
                sha: context.sha
            });

  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Environment
        run: |
          php .github/release.php current >> $GITHUB_ENV

      - name: Build TGZ
        run: |
          rm -rf .gitignore
          rm -rf .git
          rm -rf .github
          rm -rf .gitattributes
          rm -rf _test
          rm -rf lib/plugins/testing
          rm -f .editorconfig
          mkdir -p data/pages/playground
          echo "====== PlayGround ======" > data/pages/playground/playground.txt
          cd ..
          mv dokuwiki "dokuwiki-${{ env.current_version }}"
          tar -czvf "dokuwiki-${{ env.current_version }}.tgz" dokuwiki-${{ env.current_version }}
          rm -rf "dokuwiki-${{ env.current_version }}"
          mkdir dokuwiki
          mv "dokuwiki-${{ env.current_version }}.tgz" dokuwiki/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dokuwiki-${{ env.current_version }}.tgz


#      - name: Setup SSH Key
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          # generate with ssh-keyscan -H <server>
#          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
#
#      - name: Deploy to Server
#        run: |
#          scp "dokuwiki-${{ steps.get_version.outputs.VERSION }}.tgz" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:htdocs/src/dokuwiki/
#          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd htdocs/src/dokuwiki/ && tar -xzvf dokuwiki-${{ steps.get_version.outputs.VERSION }}.tgz"
